spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/books
    password: Admin@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: '8082 '